spring:
  config:
    activate:
      on-profile: local
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:33306/WONBOARD
    username: admin
    password: admin1234
mybatis:
  mapper-locations: classpath:/mapper/*.xml
jwt:
  secret: 4oCYbGVhLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtbmZ0LXNwcmluZy1ib290LWp3dC10dXRvcmlhbOKAmQo=
app:
  config:
    file:
      path: D:/workspaces/spring/images/
---

#### DEV CONFIG ####
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:23306/WONBOARD
    username: admin
    password: admin1234
mybatis:
  mapper-locations: classpath:/mapper/*.xml
jwt:
  secret: 4oCYbGVhLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtbmZ0LXNwcmluZy1ib290LWp3dC10dXRvcmlhbOKAmQo=
app:
  config:
    file:
      path: D:/workspaces/spring/images/